// code generated by go generate - look at command.go.tmpl for source file
package shelly

/*
 > Command Schedule.Create
 > This method creates a new schedule job
*/

// ScheduleCreateRequest is the request of Create.
type ScheduleCreateRequest struct {
	// RPC methods and arguments to be invoked when the job gets executed. It must contain at least one valid object. There is a limit of 5 calls per schedule
	Calls []ScheduleCreateRequestCalls `json:"calls"`
	// true to enable the execution of this job, false otherwise. It is true by default.
	Enable bool `json:"enable"`
	// As defined by cron. Note that leading 0s are not supported (e.g.: for 8 AM you should set 8 instead of 08).
	Timespec string `json:"timespec"`
}

// Extra ScheduleCreateRequestCalls is the request of ScheduleCreateRequestCalls.
type ScheduleCreateRequestCalls struct {
	// Name of the RPC method
	Method string `json:"method"`
	// The parameters used to invoke the RPC call. If the call requires no parameters params will be omitted
	Params interface{} `json:"params"`
}

// ScheduleCreateResponse is the response of Create.
type ScheduleCreateResponse struct {
}

// readResponse reads the response into the given interface.
func (r *ScheduleCreateResponse) readResponse(reader *responseReader) error {
	if reader.Response == nil {
		return ErrInvalidResponse
	}
	return reader.Read(r)
}

// Create This method creates a new schedule job
func (c ScheduleClient) Create(args ScheduleCreateRequest) (resp *ScheduleCreateResponse, err error) {
	reader := NewResponseReader()

	if err = c.call("Schedule.Create", args, &reader.Response); err != nil {
		return
	}

	resp = &ScheduleCreateResponse{}
	return resp, resp.readResponse(reader)
}

/*
 > Command Schedule.Update
 > This method updates an existing schedule job
*/

// ScheduleUpdateRequest is the request of Update.
type ScheduleUpdateRequest struct {
	// RPC methods and arguments to be invoked when the job gets executed. It must contain at least one valid object. There is a limit of 5 calls per schedule
	Calls []ScheduleUpdateRequestCalls `json:"calls"`
	// true to enable the execution of this job, false otherwise. It is true by default.
	Enable bool `json:"enable"`
	// The numeric ID of the Schedule component instance
	Id float64 `json:"id"`
	// As defined by cron. Note that leading 0s are not supported (e.g.: for 8 AM you should set 8 instead of 08).
	Timespec string `json:"timespec"`
}

// Extra ScheduleUpdateRequestCalls is the request of ScheduleUpdateRequestCalls.
type ScheduleUpdateRequestCalls struct {
	// Name of the RPC method
	Method string `json:"method"`
	// The parameters used to invoke the RPC call. If the call requires no parameters params will be omitted
	Params interface{} `json:"params"`
}

// ScheduleUpdateResponse is the response of Update.
type ScheduleUpdateResponse struct {
	// Current revision number of the schedule instances
	Rev float64 `json:"rev"`
}

// readResponse reads the response into the given interface.
func (r *ScheduleUpdateResponse) readResponse(reader *responseReader) error {
	if reader.Response == nil {
		return ErrInvalidResponse
	}
	return reader.Read(r)
}

// Update This method updates an existing schedule job
func (c ScheduleClient) Update(args ScheduleUpdateRequest) (resp *ScheduleUpdateResponse, err error) {
	reader := NewResponseReader()

	if err = c.call("Schedule.Update", args, &reader.Response); err != nil {
		return
	}

	resp = &ScheduleUpdateResponse{}
	return resp, resp.readResponse(reader)
}

// Getrev returns the rev value.
func (r *ScheduleUpdateResponse) GetRev() float64 {
	return r.Rev
}

/*
 > Command Schedule.List
 > This method returns a list of all schedule jobs
*/

// ScheduleListRequest is the request of List.
type ScheduleListRequest struct {
}

// ScheduleListResponse is the response of List.
type ScheduleListResponse struct {
	// Each entry is a schedule job object
	Jobs []ScheduleListResponseJobs `json:"jobs"`
	// Current revision number of the schedule instances
	Rev float64 `json:"rev"`
}

// ScheduleListResponseJobs is the response of ScheduleListResponseJobs.
type ScheduleListResponseJobs struct {
	// RPC methods and arguments to be invoked when the job gets executed. It must contain at least one valid object. There is a limit of 5 calls per schedule
	Calls []ScheduleListResponseJobsCalls `json:"calls"`
	// true to enable the execution of this job, false otherwise. It is true by default.
	Enable bool `json:"enable"`
	// The numeric ID of the Schedule component instance
	Id float64 `json:"id"`
	// As defined by cron. Note that leading 0s are not supported (e.g.: for 8 AM you should set 8 instead of 08).
	Timespec string `json:"timespec"`
}

// ScheduleListResponseJobsCalls is the response of ScheduleListResponseJobsCalls.
type ScheduleListResponseJobsCalls struct {
	// Name of the RPC method
	Method string `json:"method"`
	// The parameters used to invoke the RPC call. If the call requires no parameters params will be omitted
	Params interface{} `json:"params"`
}

// readResponse reads the response into the given interface.
func (r *ScheduleListResponse) readResponse(reader *responseReader) error {
	if reader.Response == nil {
		return ErrInvalidResponse
	}
	return reader.Read(r)
}

// List This method returns a list of all schedule jobs
func (c ScheduleClient) List(args ScheduleListRequest) (resp *ScheduleListResponse, err error) {
	reader := NewResponseReader()

	if err = c.call("Schedule.List", args, &reader.Response); err != nil {
		return
	}

	resp = &ScheduleListResponse{}
	return resp, resp.readResponse(reader)
}

// Getjobs returns the jobs value.
func (r *ScheduleListResponse) GetJobs() []ScheduleListResponseJobs {
	return r.Jobs
}

// Getrev returns the rev value.
func (r *ScheduleListResponse) GetRev() float64 {
	return r.Rev
}

// GetCalls returns the calls value.
func (r *ScheduleListResponseJobs) GetCalls() []ScheduleListResponseJobsCalls {
	return r.Calls
}

// GetEnable returns the enable value.
func (r *ScheduleListResponseJobs) GetEnable() bool {
	return r.Enable
}

// GetId returns the id value.
func (r *ScheduleListResponseJobs) GetId() float64 {
	return r.Id
}

// GetTimespec returns the timespec value.
func (r *ScheduleListResponseJobs) GetTimespec() string {
	return r.Timespec
}

// GetMethod returns the method value.
func (r *ScheduleListResponseJobsCalls) GetMethod() string {
	return r.Method
}

// GetParams returns the params value.
func (r *ScheduleListResponseJobsCalls) GetParams() interface{} {
	return r.Params
}

/*
 > Command Schedule.Delete
 > This method deletes an existing schedule job
*/

// ScheduleDeleteRequest is the request of Delete.
type ScheduleDeleteRequest struct {
	// The numeric ID of the Schedule component instance
	Id float64 `json:"id"`
}

// ScheduleDeleteResponse is the response of Delete.
type ScheduleDeleteResponse struct {
	// Current revision number of the schedule instances
	Rev float64 `json:"rev"`
}

// readResponse reads the response into the given interface.
func (r *ScheduleDeleteResponse) readResponse(reader *responseReader) error {
	if reader.Response == nil {
		return ErrInvalidResponse
	}
	return reader.Read(r)
}

// Delete This method deletes an existing schedule job
func (c ScheduleClient) Delete(args ScheduleDeleteRequest) (resp *ScheduleDeleteResponse, err error) {
	reader := NewResponseReader()

	if err = c.call("Schedule.Delete", args, &reader.Response); err != nil {
		return
	}

	resp = &ScheduleDeleteResponse{}
	return resp, resp.readResponse(reader)
}

// Getrev returns the rev value.
func (r *ScheduleDeleteResponse) GetRev() float64 {
	return r.Rev
}

/*
 > Command Schedule.DeleteAll
 > This method deletes all existing schedule jobs
*/

// ScheduleDeleteAllRequest is the request of DeleteAll.
type ScheduleDeleteAllRequest struct {
}

// ScheduleDeleteAllResponse is the response of DeleteAll.
type ScheduleDeleteAllResponse struct {
	// Current revision number of the schedule instances
	Rev float64 `json:"rev"`
}

// readResponse reads the response into the given interface.
func (r *ScheduleDeleteAllResponse) readResponse(reader *responseReader) error {
	if reader.Response == nil {
		return ErrInvalidResponse
	}
	return reader.Read(r)
}

// DeleteAll This method deletes all existing schedule jobs
func (c ScheduleClient) DeleteAll(args ScheduleDeleteAllRequest) (resp *ScheduleDeleteAllResponse, err error) {
	reader := NewResponseReader()

	if err = c.call("Schedule.DeleteAll", args, &reader.Response); err != nil {
		return
	}

	resp = &ScheduleDeleteAllResponse{}
	return resp, resp.readResponse(reader)
}

// Getrev returns the rev value.
func (r *ScheduleDeleteAllResponse) GetRev() float64 {
	return r.Rev
}
