// code generated by go generate - look at command.go.tmpl for source file
package shelly

/*
 > Client Shelly
*/

// Shelly is the client for the Shelly.
type ShellyClient struct {
	client *Client
}

// Shelly returns a client for the Shelly.
func (c *Client) Shelly() *ShellyClient {
	return &ShellyClient{client: c}
}

/*
 > Client Switch
*/

// Switch is the client for the Switch.
type SwitchClient struct {
	client *Client
}

// Switch returns a client for the Switch.
func (c *Client) Switch() *SwitchClient {
	return &SwitchClient{client: c}
}
