// code generated by go generate - look at command.go.tmpl for source file
package shelly

/*
 > Client Shelly
*/

// Shelly is the client for the Shelly.
type ShellyClient struct {
	client *APIClient
}

// Shelly returns a client for the Shelly.
func (c *APIClient) Shelly() *ShellyClient {
	return &ShellyClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *ShellyClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}

/*
 > Client Switch
*/

// Switch is the client for the Switch.
type SwitchClient struct {
	client *APIClient
}

// Switch returns a client for the Switch.
func (c *APIClient) Switch() *SwitchClient {
	return &SwitchClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *SwitchClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}

/*
 > Client Light
*/

// Light is the client for the Light.
type LightClient struct {
	client *APIClient
}

// Light returns a client for the Light.
func (c *APIClient) Light() *LightClient {
	return &LightClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *LightClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}

/*
 > Client Cover
*/

// Cover is the client for the Cover.
type CoverClient struct {
	client *APIClient
}

// Cover returns a client for the Cover.
func (c *APIClient) Cover() *CoverClient {
	return &CoverClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *CoverClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}

/*
 > Client DevicePower
*/

// DevicePower is the client for the DevicePower.
type DevicePowerClient struct {
	client *APIClient
}

// DevicePower returns a client for the DevicePower.
func (c *APIClient) DevicePower() *DevicePowerClient {
	return &DevicePowerClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *DevicePowerClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}

/*
 > Client Schedule
*/

// Schedule is the client for the Schedule.
type ScheduleClient struct {
	client *APIClient
}

// Schedule returns a client for the Schedule.
func (c *APIClient) Schedule() *ScheduleClient {
	return &ScheduleClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *ScheduleClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}

/*
 > Client HTTP
*/

// HTTP is the client for the HTTP.
type HTTPClient struct {
	client *APIClient
}

// HTTP returns a client for the HTTP.
func (c *APIClient) HTTP() *HTTPClient {
	return &HTTPClient{client: c}
}

// call calls the given method with the given args and reply.
func (c *HTTPClient) call(method string, args, reply interface{}) error {
	return c.client.client.rpc.Call(method, args, reply)
}
